version: '3'
services:
  redis:
    image: redis:7.0-rc3
    container_name: redis_oc
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6379:6379'
    networks:
      - oc_network
    volumes:
      - cache_data:/data

networks:
  oc_network: {}

volumes:
  oc_volume: {}
  cache_data: { driver: local }
